CREATE TABLE `hhglobaledu`.`registration2021` ( 
`id` INT(255) NOT NULL AUTO_INCREMENT ,
`Fullname` VARCHAR(500) NOT NULL ,
`Email` VARCHAR(500) NOT NULL ,
`Contact_Number` INT(20) NOT NULL ,
`District` VARCHAR(500) NOT NULL ,
`IELTS` VARCHAR(500) NOT NULL ,
`Degree` VARCHAR(500) NOT NULL ,
`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
PRIMARY KEY (`id`));
